---
ci-deployment:
  concourse-sample:
    target_name: TO_BE_DEFINED
    pipelines:
      concourse-sample-generated:
        vars_files:
        - hello-world/consourse-sample/concourse-sample-versions.yml
      concourse-sample-cf-apps-generated:
        vars_files:
        - hello-world/consourse-sample/concourse-sample-versions.yml
