---
ci-deployment:
  bosh-sample:
    target_name: TO_BE_DEFINED
    pipelines:
      bosh-sample-generated:
        vars_files:
        - hello-world/bosh-sample/bosh-sample-versions.yml
        - shared/concourse-credentials.yml
      bosh-sample-cf-apps-generated:
        vars_files:
        - hello-world/bosh-sample/bosh-sample-versions.yml
        - shared/concourse-credentials.yml
