#@ load("@ytt:data", "data")

nothing: #@ data.values.nothing
string: #@ data.values.string
boolean: #@ data.values.bool
int: #@ data.values.int
float: #@ data.values.float

auto-injected-by-coa:
  deployment-name: #@ data.values.DEPLOYMENT_NAME
  root-deployment-name: #@ data.values.ROOT_DEPLOYMENT_NAME
