#@data/values
---
nothing: "something"
string: "((/coa-my-credhub-key))"
bool: false
int: 0
float: 0.0

DEPLOYMENT_NAME: #! This is required to be able to automatically inject value of COA_DEPLOYMENT_NAME using ytt --data-values-env COA
